### ISSUE TITLE
Lock eV, He, e-, and prestige if inaccessible

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#112]
So, if you can get 3H to decay, you will earn all of those things. Even though you can't purchase He generators, if you get enough, you *can* prestige it, earn xHe, and then turn around and use the xHe for additional dark matter. On top of that, you can use eV to purchase upgrades long before you can actually use them.

I would like to propose that all things like this are hidden and disabled before they're actually unlocked. So even if you do earn He, the system just ignores it. Prevent the player from using eV before being able to use reactions, and from buying upgrades for a mechanic they can't access. At the very least, I think we should prevent the player from prestiging any elements they haven't unlocked. That's just adding more difficulty in balancing.

**Comment by angarg12** [comment]
Showing global upgrades before the mechanics are unlocked is indeed bad design. It is in the TODO list to hide them.

However I like that you are able to prestige He before buying it.

For a novice player it may not make a difference, and just ignore it. However other players may realize that they can prestige the second element to boost dark matter production, leading to that 'aha!' moment. I want elements decay chain to be relevant in the mid game, and this is an early introduction to that concept.

My only concern there is that if you can prestige He at no cost you can prestige instantly to get xHe. But this issue persists in any case after you buy He. 

I think we will only learn through playtesting how bad this feature is in terms of balance.

**Comment by angarg12** [comment]
Draft:

Hide global upgrades that aren't unlocked.

Right now upgrades can have dependencies on other upgrades. If we make them depend on the respective upgrades that unlock their mechanic, it should take care of itself.

For the entire section it's just a matter of checking if the array of visible updates is empty or not.

**Comment by angarg12** [comment]
I have made global upgrades not visible if you don't have eV, and they also depend now on whatever upgrade unlocks them (so you can't upgrade redox if you don't have it yet).

We will take care of the rest of your points in separate tasks.
