### ISSUE TITLE
Lifetime Statistics?

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#114]
Most games of this nature track a whole battery of statistics in the player's save, and often tie them into achievements. That's something we should think about, and the sooner we start actually tracking them the more consistent they'll be.

**Comment by angarg12** [comment]
It makes my head spin to think about all the kind of things that could be tracked, but definitely I see the benefit of this.

Please feel free to make a list of desirable statistics and then we can analyse how to implement each one.

**Comment by angarg12** [comment]
With commit 2e62286 we added a function to track statistics.

In a nutshell, a statistic is a key-value pair with a scope.

Scopes can be all time, current dark run, or current exotic run for an element. Elements can be an array, or all of them. Stats from 'lower' scopes are automatically added to higher ones.

Values can be numbers, in which case are added, or anything else, in which case they are replaced.

Finally, if a key-value pair is missing from any scope, it is added.

So now we can essentially put hooks whenever we want in the code to track statistics.

I'll keep this issue open to suggest stats.

**Comment by primeprover** [comment]
A few suggestions:
The amount of exotic prestige you are gaining from each isotope. Along with this it would be nice to be able to see how much more of that isotope you need to produce another exotic prestige. I always liked how Derivative Clicker did that. 
I will post more as I think of them
