### ISSUE TITLE
Hide the Boost field on exotic prestige screen if no boost available

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#115]
I don't see a whole lot of reason to have it sitting there, saying 100% if it won't ever change before the player gets any e-.

**Comment by angarg12** [comment]
Good catch!

**Comment by angarg12** [comment]
Draft of implementation:

In the exotic matter view, if the length of the visible subatomic particles array is 0, hide the div containing this information.
