### ISSUE TITLE
Hide upgrades after purchase and/or add sorting

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#116]
Especially with the synergy upgrades. We're looking at 100+ upgrades in a very long, very painful list. At the very least being able to sort by purchased/cost would be a godsend for that. Depending on how the UI and balance work goes, I've got some ideas for a grid-based system that might look really neat for the synergy upgrades.

**Comment by angarg12** [comment]
Hiding bought upgrades is indeed in the TODO list.

By sorting you mean pre-sorting, or the option to live-sort for different criteria?

If it is pre-sorting it should be very easy to implement. Just create a build script that sorts upgrades in the desired order, just like resources.

**Comment by angarg12** [comment]
Draft:

Hiding bought upgrades:

In the visible upgrades function in the upgrades controller, ignore the ones already bought.

For extra plus points, a toggle should be added to the interface that allows to show/hide upgrades.

Sorting upgrades: 

A build script can be written to take care of this. The scripts reads the data, rearranges it and writes it back to file. The only wiring needed is to add it to the gulp build task.

We could also organise upgrades in categories, but that would need some extra logic, e.g. a new field that label upgrades, or deduce their group out of their id prefix.

**Comment by HeinousTugboat** [comment]
I actually meant live sorting. I was planning on including it in my work for #13 if you like the direction that's going. Otherwise I can work on adding it to the current UI.
