### ISSUE TITLE
Update the changelog

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#118]
The changelog hasn't been updated since version 2.

This is completely my fault. Now we should go back in time and track all the changes that have happened ever since.

The good news is that once we get it up to date it will be very easy to maintain.

Right now I am tracking all the commits that bump the version. The next step is to check what has changed in between.

**Comment by angarg12** [comment]
I came with this list of version bumps.

https://pastebin.com/Kht73VUN

There is a couple of version bumps missing, either because I made a mistake or I didn't track some changes.

For extra archaeological points I dare someone to figure out what changes happened in version 1.0.3 and 1.0.4.

**Comment by angarg12** [comment]
Note to self: I have been using versioning all wrong.

Code cleanups and tests shouldn't bump the version number. I should document the version conventions somewhere.

**Comment by HeinousTugboat** [comment]
I'd like to suggest following [semantic versioning](http://semver.org/). One of my todo lists actually involves investigating how the save system is set up, and looking into both trimming it down and doing proper version checking.

**Comment by angarg12** [comment]
I was trying to follow semantic version but failed.

I would propose this convention.

* MAJOR is a complete, backwards incompatible rework. The change from ITE to Nucleogenesis was bumping from v1 to v2. I don't think we will make any major version again.
* MINOR is introducing a complete new feature or system. I have been following this one pretty consistently.
* PATCH is bugfixes and balances, but without new functionality. Sometimes is a little bit fuzzy to define the line between patch and minor. How much of a change counts as a new feature? I would favor err on the side of minor.

Regarding saves, there is probably one very easy point of optimization. Right now each resource has two fields, number and unlocked (a boolean). If instead we set the value of the resource to null, and set it to 0 on unlock, we could save quite some space and redundancy.

**Comment by HeinousTugboat** [comment]
I've gone ahead and tagged every version bump on my fork, if you want to pull them down on your end:

https://github.com/HeinousTugboat/nucleogenesis/releases

As for conventions, I mostly agree. One thing I think would be helpful is I think you should only bump the version any time you're *publishing* changes. So, for instance, if you update the actual webpage once a week, I would only bump the version on the repo when you do that. The local version shouldn't really matter.

I agree with Major versions. If not a complete rebuild, a major overhaul or expansion would suit. Minor versions, I also agree with. For patch versions, I think it's really just simplest to bump it every time you push complete changes publicly. So if we fix 20 bugs, but we don't update the page, then we don't increment the patch version. If we fix one bug but push it immediately, then I think we should increment it immediately.

> Regarding saves, there is probably one very easy point of optimization.

I'll go ahead and open a new issue for that then! :-D

**Comment by HeinousTugboat** [comment]
One other thing. I would suggest maybe using milestones for features. So, for instance, maybe assign #109 to Milestone 2.6, #22 to Milestone 2.7, etc. That way we can prioritize, too.

**Comment by HeinousTugboat** [comment]
Here are two more resources to look into if you're interested:

* [Changelog Best Practices](http://keepachangelog.com/en/1.0.0/)
* [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages)

There are tools you can use to partially automate changelogs if you stick to a consistent format with the messaging. They might be beneficial for us. I'll spend some time compiling old changes into the wiki, as well.

**Comment by angarg12** [comment]
Thanks a lot for the tagging and wiki entry!

I'll go through it and fill in the changelog.txt when I have some time.

**Comment by angarg12** [comment]
On retrospect I realise how inconsistent I was tagging versions and how useless some of them are.

From now on I take your suggestion and we will bump PATCH only on release. That way each version will have at least a good handful of changes.

**Comment by angarg12** [comment]
The information is now [on the wiki](https://github.com/angarg12/nucleogenesis/wiki/Working-Changelog).
