### ISSUE TITLE
Diegetic Upgrades and Generator Limits!

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#119]
So, like we talked about in #104 and I briefly mentioned in #13, I think it would be very beneficial for us to implement restrictions on the number of kinds of generators that can be active at any given time. Initially, I would propose we limit it to just 2. This will allow the Hydrogen to be played through, and then allow the player to get a feel for running two elements side by side. Once they start getting into reactions, then we should allow them to purchase a 3rd set of generators so they can start delving more deeply into complex molecules. Additionally, this will force the player to strategize at any given time. If they're wanting to focus on eV, they'll want to pick strongly electronegative elements. If they're wanting to discover more nuclides, then they'll want to focus on using decay chains, presumably picking complementary elements.

This gives us two more very strong benefits. First, it greatly simplifies the UI needs, as we only ever have to present a very small fraction of the total available reactions to the player. Second, it makes the actual process of managing generators simpler. This will help allow players to focus on strategy as opposed to simply optimally managing dozens of different elements.

**Comment by angarg12** [comment]
I love this idea. I have been thinking about this a bit and I think it is all advantages.

I would start with 1 slot for early game and possibly introduce more later.

To check that we are in the same page this is how I see it now.

I imagine this feature working pretty much like race selection in Realm Grinder. You start with H and can buy generators and upgrades. On exotic prestige you get to choose what element you want to generate next run (if you only have 1 it will be automatic). At any given moment you can only buy stuff from or prestige your current active element. Finally, exotic upgrades and derive resources (e.g. decay) persists even if you change element (with the exception of a dark prestige).

One thing that is not quite clear to me now is how to handle resources from elements that are not 'active'. Probably there a resource dashboard is necessary.

Anyway this looks like it will be a large feature, so we can spend some time designing it.

**Comment by HeinousTugboat** [comment]
That's very close to what I was imagining, actually! Only extending "current active element" to multiple elements in mid and endgame. So you start with just one, but then you buy an upgrade with dark matter or eV and can now use two.

> One thing that is not quite clear to me now is how to handle resources from elements that are not 'active'. Probably there a resource dashboard is necessary.

Presumably, you wouldn't have any resources from inactive elements, as you lose all of them when you prestige. So we would just tragic what exotics you have. The other part of my idea was that you could then use exotics to restart an element if you want to change it before prestiging with dark matter.

If you're referring to molecules (which I still have very little exposure to, I'm working on it!), then I feel like we're going to pretty much have to break those apart from the generator/element paradigm. They're too deeply disconnected and complex.

I had an idea you can see in my prototype on #13, of having a Laboratory tab instead of Reaction/Redox tabs. The lab would be where you would store molecules, and perform reactions/experiments/whatnot. We could even require specific kinds of storage upgrades. Like, you can't store highly reactive elements without a certain eV upgrade, or you can't store highly radioactive elements without a storage/shielding upgrade.

**Comment by angarg12** [comment]
I like the idea of keeping the exotic progress that you made in an element even after you swap it, so that you can come back later and continue (until you do a dark prestige obviously). It would be very interesting from the strategy point of view to make progress on different directions sequentially.

From the GUI perspective the only requirement is to able to tab to see the exotic upgrades of element that are not currently active. I'm guessing it would be not so hard to make it very clear that these elements are not interactive at the moment e.g. with a grayout.

One way that you can generate resources of an inactive element is decay. But again a dashboard that displays a summary of all resources should make this more manageable.

One small bit that concerns me is that if you can only create resources for your currently active element, how to handle reactions? Reactions now work because you generate all resources at once. However with this paradigm if you wanted a reaction with C and O, you would need to activate both of them together. This complicates for reactions that may have up to 4 different elements involved.

Then again, this may turn out to not be a problem. I would rather prototype this mechanic and playtest it before making more assumptions.

**Comment by HeinousTugboat** [comment]
> One small bit that concerns me is that if you can only create resources for your currently active element, how to handle reactions? Reactions now work because you generate all resources at once.

That was why I kept stressing on having multiple simultaneously active elements, and an important part of the strategy aspect. Say I want to explore organics. I would need to have 3 active elements, and they would need to be Carbon, Oxygen and Hydrogen. Then I could react those as necessary. If I want to shift over into Nitrogen, I could prestige Oxygen out, bank the xO, and swap in xN for its place.

We could also implement some method of storing or saving compounds instead of forcing them to prestige. I hope this makes sense. I would suggest allowing up to 6 or 7 active elements at end game so players don't have to switch around too much for more complex reaction chains.

**Comment by angarg12** [comment]
I think the most complex reactions involve 4 different elements in a double replacement, so 4 seems like a good maximum number. In any case it is better to prototype this feature first and see how it works, and then adjust it as needed.

**Comment by HeinousTugboat** [comment]
I had just remembered that [this game exists](http://www.kongregate.com/games/newproject1/idle-evolution). I'm not sure if you've seen it before, but it has some similarities to this project. There might be some decent ideas in it we could think about!

**Comment by angarg12** [comment]
Oh yes I faintly remember this one from a while ago. It uses your concept of assigning generators to elements.

I found they have a [steam released](http://store.steampowered.com/app/577730/Idle_Evolution/) that looks more polished. Definitely a good source of inspiration.
