### ISSUE TITLE
Analyze and trim savefile

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#120]
We should update the saving mechanisms to use delta saves where ever possible. Right now it's a pretty hefty file.

**Comment by angarg12** [comment]
I wonder if there is any JS library that gives you a JSON object as a diff of two objects and allows you to merge them back.

If that is the case it should be fairly easy to implement this feature.

**Comment by HeinousTugboat** [comment]
I don't think it'd be particularly hard to do, honestly. I just threw this snippet together. It's very simple, and doesn't really cover arrays but they're easy enough to trim and copy with `Array.filter()` and `newArr = [...srcArr]`.

```javascript
// Current instance
let sourceObj = {
    a: 'Test',      // Changed from default
    b: undefined,   // Explicitly marked undefined
    c: 'Bar'        // Same as default
    // No d present at all
};

// Default values we expect
let defaultObj = {
    a: 'One',
    b: 'Two',
    c: 'Bar',
    d: 'Foo'
};

// Trim the object down
let trimmedObj = {};
for (let label in sourceObj) {
    if (sourceObj[label] !== defaultObj[label]) {
        trimmedObj[label] = sourceObj[label];
    }
}

// Fresh copy    
let newObj = Object.assign({},defaultObj,trimmedObj);

console.log('src', sourceObj);      // { a: "Test", b: undefined, c: "Bar" }
console.log('def', defaultObj);     // { a: "One", b: "Two", c: "Bar", d: "Foo" }
console.log('trim', trimmedObj);    // { a: "Test", b: undefined }
console.log('new', newObj);         // { a: "Test", b: undefined, c: "Bar", d: "Foo" }
```

When I get the time I can sit down and hack on the save system to start implementing this. :-)

**Comment by angarg12** [comment]
I prefer to keep this kind of util functions in external packages as dependencies. Do you think you could push it to your repo and we reference it with bower? That is, for example, what I do with [versionCompare](https://github.com/angarg12/version_compare).

**Comment by angarg12** [comment]
@HeinousTugboat proposed to use Prototype inheritance to inherit the player object from startPlayer. That would reduce the size of the player object easily.

**Comment by angarg12** [comment]
We did a little bit of trimming to the save file.

We didn't quite apply the prototype approach, but unless it becomes a bigger issue or someone contributes it, we won't continue working on this.
