### ISSUE TITLE
Compound Naming?

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#125]
So, Uranium Hexaflouride is listed as F6U in the game. From reading on it, it looks like it's generally listed as [UF6](https://en.wikipedia.org/wiki/Uranium_hexafluoride) instead. I was wondering if there was a system you were using for naming, or where the compound formulas came from. Should they be changed to their commonly used versions?

**Comment by angarg12** [comment]
At the beginning naming was a mess, so I decided to use [Hill notation](https://en.wikipedia.org/wiki/Chemical_formula#Hill_system). 

The build script checks that a molecule is written in Hill notation, otherwise it throws a warning. I think F6U is correct in Hill notation.

**Comment by HeinousTugboat** [comment]
That makes sense! Yeah, it looks like it's correct in Hill notation.
