### ISSUE TITLE
Dashboard displays every element 3 times

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#131]
See example:

![image](https://user-images.githubusercontent.com/15902166/30784854-1c152396-a12b-11e7-9887-075fb747a7df.png)

**Comment by angarg12** [comment]
Yeah, that's on purpose. The idea is that players can look up and compare several resources at once.

Ideally it would show only 1 column, and at the top there would be a "+" button that adds more on demand.

How does that sound?
