### ISSUE TITLE
Production should work with slots

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#133]
As suggested by @HeinousTugboat instead of all elements producing at all times, we should use a slot system where players place elements for production.

This is the plan:

* Generators, upgrades and exotic upgrades are removed from each element.
* A new element_slots array is added.
* Each element in the element_slots is a object that contains an element and generators, upgrades and exotic upgrades.
* All operations happen on element slots.
* On prestige, the slot gets reset. Then, the player selects a new element (or the same) to populate the slot.
* The game starts with 1 slot. More slots can be purchased as dark upgrades.

Using this system players can only generate a limited amount of elements at any given point of time. All these elements will be visible on screen.

**Comment by angarg12** [comment]
I just wanted to give a heads up on this issue since I am working on it at the moment.

This change is massive and affects almost the whole codebase. Also it has minor changes that ripple through other parts of the game. I am trying to release a first version with only 1 slot and no swaps but even that will take a short while.

**Comment by HeinousTugboat** [comment]
Let me know if I can be of assistance! You could put your update on a branch and upload it here if you want any help with the implementation.

**Comment by angarg12** [comment]
Thanks a lot!

I couldn't think of any sane way of dividing and paralelising it. This task requires a massive refactoring in the player object, and therefore almost all mechanics that use it. I'm also always going back and forth changing and fixing things.

I'll let you know if I can think of anything.

**Comment by angarg12** [comment]
This one was a BIG refactor so I will be wary of incoming bugs.

A few comments about the implementation.

* Now players have an array element_slots where they store an element_slot object.
* An element_slot contains the id of the element, generators, upgrades, reactions and redoxes.
* The array is initially size 1. You can buy dark upgrades to extend it.
* Each relevant view (matter, upgrades, etc.) iterates on the array and displays the element. So you can see all the active elements one after another.
* To reset an element set it to null (prestige).
* When an slot is empty (null value), an element select menu is displayed. It contains a row of buttons with all purchased elements. Click on one to select it. Selecting an element populates that slot with a fresh copy of the element_slot object.
* You cannot select the same element twice.
* There is also a convenience redox/reaction caching mechanic. If you prestige an element and choose it again you will get back your redoxes/reactions. The cache is cleared on the session.

As a side effect I implemented the concept of 'fire_once_function'.

For extending the array I needed an upgrade that gets executed only once, on purchase. The code allows to define functions for upgrades that get executed on each loop, but unless you add some ugly workaround you cannot execute them only once.

So now for any upgrade you can define a fire_once_function. This function receives the player object and is executed only once, when the upgrade is purchased.

This feature may be overengineered but I didn't want to hardcode this logic in the upgrade function and keeps it consistent with the rest of upgrades.
