### ISSUE TITLE
Swarm numberforma doesn't work well with small numbers (< 1)

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#136]
We have a few instances where we need small numbers or up to 4 significant digits, e.g. isotope ratios or elements abundance.

It turns out swarm numbers format doesn't play well with this. For instance, if you have 1e-8, it will display just 0.

The best solution would be to extend the library to support very small numbers, probably following the format (mini, micro, nano, etc.), but for the time being the fastest fix is to drop pretty numbers for these values and just display plain JS.

**Comment by HeinousTugboat** [comment]
See erosson/swarm-numberformat#19

**Comment by angarg12** [comment]
Thanks a lot for the heads up. I'm not not too much in a hurry so we can wait to see what comes out of it.

**Comment by primeprover** [comment]
There has been another post at the above link

**Comment by angarg12** [comment]
Yes, I'm aware, I'll try it out :slightly_smiling_face:
