### ISSUE TITLE
Periodic Table Dark Matter..

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#141]
So, if you set the Periodic Table to spend all of your dark matter, it happily throws away 5e20 dark matter to unlock Lithium..

It should probably stop once it's had enough to unlock a particular element.

**Comment by angarg12** [comment]
This is intended, the way that it's set up.

When you put in more DM you increase the chance of success, but all that DM is consumed in the process. In order words, it isn't iterative and stop as soon as an element gets unlocked.

However I do agree that it is bad UX to spend all your resources. I would propose the following:

* Cap the maximum DM you can spend, e.g. to 100.
* Put a very clear disclaimer saying that all those resources will be consumed.
