### ISSUE TITLE
Upgrades locked by exotic upgrades are not visible

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#142]
Upgrades gated by exotic upgrades, such as x3, are not visible right now.

The reason is that the list of dependencies references upgrades that don't exist anymore.

**Comment by Stevel-Knievel** [comment]
Possible extension of this bug, not sure, but Boost 2 upgrades are missing too

**Comment by angarg12** [comment]
Thanks for the report.

We should include a sanity check in the build script that checks that all dependencies do exists, to avoid these kind of bugs in the future.
