### ISSUE TITLE
Add the ability to save export as file instead of text

### ISSUE THREAD

**Issue by HeinousTugboat** [angarg12/incremental_table_elements#149]
Was talking with Mpmpmpmp in discord and he suggested it from another game. Shouldn't be too hard to do, I've built something that can convert files to b64 and back before, so I can port that code into the game. Let me know what you think!

**Comment by angarg12** [comment]
Sure thing.

**Comment by angarg12** [comment]
Today primeprover lost his savefile while trying to export it, and importing a previous one by mistake.

Hopefully this feature will also fix those kind of problems.
