### ISSUE TITLE
Prestige Malfunction

### ISSUE THREAD

**Issue by Stevel-Knievel** [angarg12/incremental_table_elements#154]
When attempting to EM prestige, I am allowed by the game to prestige Helium, but not Hydrogen or Nitrogen (running all 3 elements at once). Can attach screenshots if necessary.

**Comment by angarg12** [comment]
Yes, please share an screenshot.

**Comment by Stevel-Knievel** [comment]
![image](https://user-images.githubusercontent.com/33704300/33337724-5beb998c-d420-11e7-9481-ee815ef6ce69.png)

![image](https://user-images.githubusercontent.com/33704300/33337754-71b07ecc-d420-11e7-96c2-f65c59aec271.png)

**Comment by Stevel-Knievel** [comment]
As you can see, the button is there, but it doesn't display a quantity for obtainable EM, and the Prestige button is nonfunctional.

**Comment by angarg12** [comment]
Fixed on b43980f69d894ae4f25dcbeee234bd0fb0ad1da0
