### ISSUE TITLE
Remember hide bought upgrades option

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [angarg12/incremental_table_elements#157]
![image](https://user-images.githubusercontent.com/14184826/33392506-4da778b0-d50a-11e7-935f-df2c57b83a4e.png)
(refresh)
![image](https://user-images.githubusercontent.com/14184826/33392538-63b63830-d50a-11e7-813b-d3c0a6b162d8.png)

I'd make a PR but I frankly have no idea how to fix this.

**Comment by angarg12** [comment]
Which version are you playing? The dev version addressed this on #153.

Join our discord channel to find the super secret dev version with all the latest updates, use at your own risk! :smile:

**Comment by SIGSTACKFAULT** [comment]
oh, I heard about it from the /r/incrementalgames Discord, and then forgot about it.

[close] [fixed]
