### ISSUE TITLE
Production Measurements are Different per Resource

### ISSUE THREAD

**Issue by BobChao87** [angarg12/incremental_table_elements#176]
While playing the game and attempting to derive certain values related to the prestige system, I discovered that different resources are measured differently in the exotic matter tab. I currently only have Hydrogen unlocked, so this is by no means an exhaustive list.

Grows with Production:
 * <sup>2</sup>H
 * <sup>3</sup>H
 * H<sub>2</sub>

Grows with Quantity and Production:
 * <sup>1</sup>H
 * H<sup>-</sup>
 * H<sup>+</sup>

Resources in the Grows with Production category increase each game tick by an amount equal to the amount produced during that game tick. _i.e._ If you have 117 <sup>2</sup>H stored and the exotic matter tab reports 593 <sup>2</sup>H and the game tick produces 4 <sup>2</sup>H, then after the game tick, you end up with 121 <sup>2</sup>H stored and the exotic matter tab reporting 597 <sup>2</sup>H.<sup>*</sup>

Resources in the Grows with Quantity category increase each game tick by an amount equal to the existing amount of that resources before the game tick changes resolve and the total amount produced during that game (minus 1 for some reason). _i.e._ If you have 117 <sup>1</sup>H stored and the exotic matter tab reports 593 <sup>1</sup>H and the game tick produces 4 <sup>1</sup>H, then after the game tick, you end up with 121 <sup>1</sup>H stored and the exotic matter tab reporting 713 <sup>1</sup>H (equal to 593 + 117 + 4 - 1).<sup>*</sup>

While I suspect that the Grows with Quantity algorithm is the one that is a bug, I'm not really sure which is the bug here since Grows with Quantity has massive benefits for long-term idle periods. However, it make sense that all resources that contribute to the exotic matter production should behave the same way and consequently at least one of these algorithms would likely need to be changed.

<sup>*</sup> Examples assume that during these sample game ticks, no processes are consuming the resource in the example as that is an unnecessary complication to the math as presented. The numbers are additionally fabricated and may not represent values that are possible to achieve through normal gameplay.

**Comment by angarg12** [comment]
That is the effect of electronegativity.

Electronegativity spontaneously redoxes ions and the main isotope for each element.

So for simplicity sake, lets say you have 100 1H and 100 H-. The electronegativity gives you a 10% chance to oxidise and 5% to reduce. Then, 10 1H become H- and 5 H- become 1H, so you end up with 95 1H and 105 H-. For exotic matter purposes you produced those resources.

I hope that clarifies this issue.

**Comment by BobChao87** [comment]
The effect I'm observing seems too strong to be attributed to just electronegativity as you describe. I can have on the order of 1e9 added to the exotic matter measure for <sup>1</sup>H even when there are only 5e4 (each) of H<sup>-</sup> and H<sup>+</sup>. It seems unlikely that 100% of my <sup>1</sup>H is being converted back and forth each game tick.

I realize that you probably know more about electronegativity than I do, so for now I will close this bug and look into the issue and re-open it if I find more evidence of any issues. I guess I will also review electronegativity, since it has been a long time since I've used that for anything.

**Comment by angarg12** [comment]
Electronegativity is a fairly complex affair so it is probable there are some bugs lurking around.

Please reopen if you identify any strange behaviour.

**Comment by BobChao87** [comment]
For some final closure, it looks like this issue is gone in master after the public v2.8.0 beta cut. I could find the exact commit, but that seems moot since the issue has already resolved.
