### ISSUE TITLE
Convert JSON to JSON (with comments)

### ISSUE THREAD

**Issue by BobChao87** [angarg12/incremental_table_elements#181]
Add the ability for a preprocessor to convert existing JSON structures to JSON (with comments) to allow for acknowledgment of isotopes in various places in the source code for simpler implementation later or simple direct comments that it will not included for various reasons without bogging down the game engine by making it handle any extra data.

**Comment by angarg12** [comment]
I'm kind of reluctant to use a non-standard format since JSON works so nicely together with JS.

Since the objective is to keep some data at hand, would it be ok to create a new wiki page and track that information there?

**Comment by angarg12** [comment]
I've created this wiki page

https://github.com/angarg12/nucleogenesis/wiki/Candidate-isotopes

We could write there the information about the missing isotopes.

Let me know what you think.

**Comment by BobChao87** [comment]
Looks go to me, now we just have to convince people to use it. xD
