### ISSUE TITLE
eV does not reset on Prestige (xH)

### ISSUE THREAD

**Issue by reesylou** [angarg12/incremental_table_elements#186]
This may be intentional, as I currently only have Hydrogen open.  If so, apologies for wasting your time.  When performing an Exotic Matter Prestige (using xH), the value for eV does not reset and retains the eV generated prior to Prestige.

**Comment by angarg12** [comment]
Yes, this is intentional. It helps to accelerate prestiges and you can use it smartly to progress faster 😃
