### ISSUE TITLE
Fusion settings can cause game to freeze unrecoverably

### ISSUE THREAD

**Issue by jjclark1982** [angarg12/incremental_table_elements#191]
I selected Sn-126 and Po-210 for Fusion.

After reloading the game in this state, the Fusion tab shows the "Beam and Target" column, but not the "Product" column. After viewing this tab, the game time stops advancing, and this error message appears in the console: 

```
TypeError: Cannot read property '336' of undefined
    at Object.ct.getProductIsotope (app.min.js:6332)
    at fn (eval at compile (angular.js:16387), <anonymous>:4:941)
    at m.$digest (angular.js:19095)
    at m.$apply (angular.js:19463)
    at angular.js:14236
```

The element dropdowns are disabled, so I cannot get it out of this state by selecting different elements. I have tried all types of prestige and reloading, but this game is thoroughly stuck. Here is the save data: https://pastebin.com/crR8F8dq

**Comment by angarg12** [comment]
Thanks for the report, I have a good idea of what might be going on.

I'll take a look and update you with my findings.

**Comment by angarg12** [comment]
I pushed a fix, it should be live shortly.

Please check whether it works.

**Comment by angarg12** [comment]
BTW I double checked your save and although the bug is fixed, the save is stuck on fusion. Fixing it requires manual intervention since there is no way to stop a fusion.

I could send a fixed save your way. I was wondering though if it would be good to introduce a systemic way to fix these cases in the game. I need to think a bit about it.

**Comment by jjclark1982** [comment]
Thanks for fixing the freezing error. I set `active` and `running` to `false` in the fusion save data and the dropdowns became usable again.

I think it would be safe to automatically disable `active` and `running` when visiting the fusion tab for the first time and there is no valid product.
