### ISSUE TITLE
Fusion products don't become available for future fusion

### ISSUE THREAD

**Issue by Brilliand** [angarg12/incremental_table_elements#192]
In an attempt to reach some of the higher elements, I fused some Sodium-25, intending to then fuse it with  Mercury-204.  However, the Sodium-25 didn't show up in the list of possible fusion ingredients.  I also tried Oxygen-19, with the same result.

It looks like fusion products aren't being counted in my "exotic run" stats, although they are counted in my "dark run" stats.

**Comment by angarg12** [comment]
Thanks for the report, could you please attach a savegame?

Exotic runs only include resources from elements that you have active, so it makes sense that it doesn't include isotopes from other elements.

**Comment by angarg12** [comment]
I have been looking at a save I have and been able to reproduce it.

Also I was wrong about exotic runs. I think I need to revisit some of my assumptions and tinker with the code a little.
