### ISSUE TITLE
Add a molecule: Potassium thiocyanate (KSCN)

### ISSUE THREAD

**Issue by loader3229** [angarg12/incremental_table_elements#194]
Add a molecule: Potassium thiocyanate (KSCN)

**Comment by angarg12** [comment]
Hello, thanks a lot for the suggestion.

Currently, as you might have noticed, I have only added molecules with 2 elements to the game.

The only reason is that I had to stop somewhere, and I arbitrarily decided to stop at 2 elements. If I allowed bigger molecules (3, 4, more elements) I could just keep adding and adding and never stop.

It still wouldn't be a big deal to add this one molecule as an exception. Do you have a suggested path on how this molecule would be built?
