### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by iLikeGrape** [angarg12/incremental_table_elements#200]
okkkkkk so I have no clue how this game works at all or what I'm supposed to do other than buy generators. like I got H3 but it isn't decaying and like wtf is a redox or exotic matter? it would be really nice to have a tutorial or blurb or something when you unlock anything important

**Comment by elementgermanium** [comment]
As far as I'm aware, the game's no longer in development. Last update was a bug fix two years ago. It'd be a pleasant surprise to see more, though.

**Comment by angarg12** [comment]
Hello there.

If I recall correctly H3 has a very high half life, so you'll need tons of it for decay to happen. I believe you'll need to go through a few "prestige" cycles to get that much.

Exotic matter is the first layer of prestige in the game. It resets your progress for a certain element but grants you boosts and some other bonuses.

Redox is another mechanic where you can generate isotopes for elements. To begin with Hydrogen you can't do much, but you can use it to play with energy, electrons and H.

It's been a while but I see that I replaced "goals" with achievements. Aiming for achievements should guide you towards unlocking new game mechanics. At some point everything is available so it's a more self-directed gameplay aimed at gathering all achievements.

Sadly I don't have the passion to continue working on this game so I don't think I will do further development. However as open source I'd be happy to merge contributions from the community.

If you are still playing and want to know more please don't hesitate to ask.
