### ISSUE TITLE
Make the update in a copy and update all at once

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#39]
Right now the update function works in place which means that the order in which updates is executed affects the outcome.

Update should happen in a copy so that we get the update from a step to the next.

**Comment by Unihedro** [comment]
How about using the [appcache](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) protocol, which allows letting the browser handle updates (and provide offline functionality)?

**Comment by angarg12** [comment]
I don't think appcache helps with the problem I'm trying to solve. Also it is marked as deprecate.

Thanks for the suggestion.
