### ISSUE TITLE
Beta decay?

### ISSUE THREAD

**Issue by mentalzenith** [angarg12/incremental_table_elements#5]
What does Beta decay does?
I'm not getting any HE from it
The first element unlocked in the table beside H is O
Is this bugged?

Firefox 47.0.1

My Save:
`eyJpbnRybyI6eyJiYW5uZXIiOnRydWUsIm1lbnUiOnRydWUsImNvbnRlbnQiOnRydWV9LCJlbGVtZW50c191bmxvY2tlZCI6MiwiY3VycmVudF90aGVtZSI6ImN5Ym9yZyIsInZlcnNpb24iOiIwLjkuMTEiLCJyZXNvdXJjZXMiOnsiSCI6eyJudW1iZXIiOjU1ODY4NDQzNDYzNDc5LCJpc19uZXciOmZhbHNlLCJ1bmxvY2tlZCI6dHJ1ZX0sIkgtIjp7Im51bWJlciI6Nzk3NDQ2MywiaXNfbmV3IjpmYWxzZSwidW5sb2NrZWQiOnRydWV9LCIySCI6eyJudW1iZXIiOjY3ODU5MjA4NDY2LCJpc19uZXciOmZhbHNlLCJ1bmxvY2tlZCI6dHJ1ZX0sIjNIIjp7Im51bWJlciI6NTkwMTEwODIxLCJpc19uZXciOmZhbHNlLCJ1bmxvY2tlZCI6dHJ1ZX0sIkgyIjp7Im51bWJlciI6MTU0NzI4ODQwLCJpc19uZXciOmZhbHNlLCJ1bmxvY2tlZCI6dHJ1ZX0sIkhlIjp7Im51bWJlciI6MCwiaXNfbmV3Ijp0cnVlLCJ1bmxvY2tlZCI6ZmFsc2V9LCIzSGUrMSI6eyJudW1iZXIiOjU4NzcsImlzX25ldyI6dHJ1ZSwidW5sb2NrZWQiOnRydWV9LCJPIjp7Im51bWJlciI6NzAxMzU1LCJpc19uZXciOmZhbHNlLCJ1bmxvY2tlZCI6dHJ1ZX0sIk8yIjp7Im51bWJlciI6MTI0OTg1MDYsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwiTzMiOnsibnVtYmVyIjoyOTEsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwiMTdPIjp7Im51bWJlciI6MTAzNzgsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwiMThPIjp7Im51bWJlciI6NTMzNjUsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwiSDJPIjp7Im51bWJlciI6MCwiaXNfbmV3Ijp0cnVlLCJ1bmxvY2tlZCI6ZmFsc2V9LCJlLSI6eyJudW1iZXIiOjU4MTAsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwibiI6eyJudW1iZXIiOjEsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwicCI6eyJudW1iZXIiOjc5NzQzOTYsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfSwiZW5lcmd5Ijp7Im51bWJlciI6MjQyNjc1NjEwLjc1MDQsImlzX25ldyI6ZmFsc2UsInVubG9ja2VkIjp0cnVlfX0sImVsZW1lbnRzIjp7IkgiOnsidW5sb2NrZWQiOnRydWUsInVwZ3JhZGVzIjp7IlRpZXIgMS0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS0yIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS0zIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS00Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS01Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS02Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS03Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMS04Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi0yIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi0zIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi00Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi01Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi02Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi03Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMi04Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDMtMSI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDMtMiI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDMtMyI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDMtNCI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDMtNSI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDMtNiI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDMtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAzLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNC0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC0yIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC0zIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC00Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC01Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC02Ijp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDQtOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA1LTEiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA1LTIiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA1LTMiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA1LTQiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA1LTUiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA1LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNS03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDUtOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA2LTEiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA2LTIiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA2LTMiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA2LTQiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA2LTUiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA2LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNi03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDYtOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA3LTEiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA3LTIiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA3LTMiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA3LTQiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA3LTUiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA3LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNy03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDctOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA4LTEiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA4LTIiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA4LTMiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA4LTQiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciA4LTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOC02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDgtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA4LTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOS0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgOS0yIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgOS0zIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgOS00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDktNSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA5LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOS03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDktOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMC0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMTAtMiI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDEwLTMiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciAxMC00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEwLTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTAtNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMC03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEwLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTEtMSI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDExLTIiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciAxMS0zIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDExLTQiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTEtNSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMS02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDExLTciOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTEtOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMi0xIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEyLTIiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTItMyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMi00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEyLTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTItNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMi03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEyLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTMtMSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMy0yIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEzLTMiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTMtNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMy01Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEzLTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTMtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMy04Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDE0LTEiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTQtMiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxNC0zIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDE0LTQiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTQtNSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxNC02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDE0LTciOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTQtOCI6eyJib3VnaHQiOmZhbHNlfX0sImdlbmVyYXRvcnMiOnsiVGllciAxIjp7ImxldmVsIjo0MTJ9LCJUaWVyIDIiOnsibGV2ZWwiOjM3Mn0sIlRpZXIgMyI6eyJsZXZlbCI6MzEwfSwiVGllciA0Ijp7ImxldmVsIjoyNjF9LCJUaWVyIDUiOnsibGV2ZWwiOjIxNH0sIlRpZXIgNiI6eyJsZXZlbCI6MTg2fSwiVGllciA3Ijp7ImxldmVsIjoyNjR9LCJUaWVyIDgiOnsibGV2ZWwiOjEzNn0sIlRpZXIgOSI6eyJsZXZlbCI6MTM4fSwiVGllciAxMCI6eyJsZXZlbCI6NzZ9LCJUaWVyIDExIjp7ImxldmVsIjozMH0sIlRpZXIgMTIiOnsibGV2ZWwiOjF9LCJUaWVyIDEzIjp7ImxldmVsIjowfSwiVGllciAxNCI6eyJsZXZlbCI6MH19fSwiTyI6eyJ1bmxvY2tlZCI6dHJ1ZSwidXBncmFkZXMiOnsiVGllciAxLTEiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciAxLTIiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciAxLTMiOnsiYm91Z2h0Ijp0cnVlfSwiVGllciAxLTQiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMS01Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEtNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxLTciOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMS04Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDItMSI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDItMiI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDItMyI6eyJib3VnaHQiOnRydWV9LCJUaWVyIDItNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAyLTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMi02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDItNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAyLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMy0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMy0yIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgMy0zIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDMtNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAzLTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMy02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDMtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAzLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNC0xIjp7ImJvdWdodCI6dHJ1ZX0sIlRpZXIgNC0yIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDQtMyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA0LTQiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNC01Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDQtNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA0LTciOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNC04Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDUtMSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA1LTIiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNS0zIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDUtNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA1LTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNS02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDUtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA1LTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNi0xIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDYtMiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA2LTMiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNi00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDYtNSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA2LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNi03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDYtOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA3LTEiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNy0yIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDctMyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA3LTQiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNy01Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDctNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA3LTciOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgNy04Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDgtMSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA4LTIiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOC0zIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDgtNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA4LTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOC02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDgtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA4LTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOS0xIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDktMiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA5LTMiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOS00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDktNSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciA5LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgOS03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDktOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMC0xIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEwLTIiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTAtMyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMC00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEwLTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTAtNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMC03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEwLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTEtMSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMS0yIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDExLTMiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTEtNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMS01Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDExLTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTEtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMS04Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEyLTEiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTItMiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMi0zIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEyLTQiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTItNSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMi02Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEyLTciOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTItOCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMy0xIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEzLTIiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTMtMyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMy00Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEzLTUiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTMtNiI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxMy03Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDEzLTgiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTQtMSI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxNC0yIjp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDE0LTMiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTQtNCI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxNC01Ijp7ImJvdWdodCI6ZmFsc2V9LCJUaWVyIDE0LTYiOnsiYm91Z2h0IjpmYWxzZX0sIlRpZXIgMTQtNyI6eyJib3VnaHQiOmZhbHNlfSwiVGllciAxNC04Ijp7ImJvdWdodCI6ZmFsc2V9fSwiZ2VuZXJhdG9ycyI6eyJUaWVyIDEiOnsibGV2ZWwiOjEwMn0sIlRpZXIgMiI6eyJsZXZlbCI6NDd9LCJUaWVyIDMiOnsibGV2ZWwiOjE1fSwiVGllciA0Ijp7ImxldmVsIjo0fSwiVGllciA1Ijp7ImxldmVsIjo0fSwiVGllciA2Ijp7ImxldmVsIjowfSwiVGllciA3Ijp7ImxldmVsIjowfSwiVGllciA4Ijp7ImxldmVsIjowfSwiVGllciA5Ijp7ImxldmVsIjowfSwiVGllciAxMCI6eyJsZXZlbCI6MH0sIlRpZXIgMTEiOnsibGV2ZWwiOjB9LCJUaWVyIDEyIjp7ImxldmVsIjowfSwiVGllciAxMyI6eyJsZXZlbCI6MH0sIlRpZXIgMTQiOnsibGV2ZWwiOjB9fX19LCJlbmN5Y2xvcGVkaWEiOnsiSHlkcm9nZW4iOnsiaXNfbmV3IjpmYWxzZX0sIk94eWdlbiI6eyJpc19uZXciOmZhbHNlfSwiSXNvdG9wZSI6eyJpc19uZXciOmZhbHNlfSwiRWxlY3Ryb24iOnsiaXNfbmV3IjpmYWxzZX0sIlByb3RvbiI6eyJpc19uZXciOmZhbHNlfSwiTmV1dHJvbiI6eyJpc19uZXciOmZhbHNlfSwiUmFkaW9hY3Rpdml0eSI6eyJpc19uZXciOmZhbHNlfSwiSGFsZi1saWZlIjp7ImlzX25ldyI6ZmFsc2V9LCJCZXRhIGRlY2F5Ijp7ImlzX25ldyI6ZmFsc2V9LCJFbmVyZ3kiOnsiaXNfbmV3IjpmYWxzZX0sIkVsZWN0cm9udm9sdCI6eyJpc19uZXciOmZhbHNlfSwiSW9uaXphdGlvbiBlbmVyZ3kiOnsiaXNfbmV3IjpmYWxzZX0sIkVsZWN0cm9uIGFmZmluaXR5Ijp7ImlzX25ldyI6ZmFsc2V9LCJOdWNsZWFyIGJpbmRpbmcgZW5lcmd5Ijp7ImlzX25ldyI6ZmFsc2V9LCJTeW50aGVzaXMiOnsiaXNfbmV3IjpmYWxzZX0sIklvbiI6eyJpc19uZXciOmZhbHNlfSwiTW9sZWN1bGUiOnsiaXNfbmV3IjpmYWxzZX0sIkZyZWUgcmFkaWNhbCI6eyJpc19uZXciOmZhbHNlfSwiQWxsb3Ryb3BlIjp7ImlzX25ldyI6ZmFsc2V9LCJVbnN0YWJsZSBjb21wb3VuZCI6eyJpc19uZXciOmZhbHNlfSwiV2F0ZXIgKEgyTykiOnsiaXNfbmV3Ijp0cnVlfSwiQSB3b3JkIGZyb20gdGhlIGRldmVsb3BlciI6eyJpc19uZXciOnRydWV9fSwidW5sb2NrcyI6eyJoeWRyb2dlbiI6dHJ1ZSwicGVyaW9kaWNfdGFibGUiOnRydWUsImlzb3RvcGUiOnRydWUsImlvbiI6dHJ1ZSwicmFkaW9hY3Rpdml0eSI6dHJ1ZSwiYWxsb3Ryb3BlIjp0cnVlLCJmcmVlX3JhZGljYWwiOnRydWUsInVuc3RhYmxlX2NvbXBvdW5kIjp0cnVlLCJyZWFjdGlvbnMiOnRydWUsImVsZWN0cm9uIjp0cnVlLCJwcm90b24iOnRydWUsIm5ldXRyb24iOnRydWUsImVuZXJneSI6dHJ1ZSwiaGFsZl9saWZlIjp0cnVlLCJveHlnZW4iOnRydWUsInVwZ3JhZGUiOnRydWUsImlvbml6YXRpb25fZW5lcmd5Ijp0cnVlLCJlbGVjdHJvbl9hZmZpbml0eSI6dHJ1ZSwibnVjbGVhcl9iaW5kaW5nX2VuZXJneSI6dHJ1ZSwiYmV0YV9kZWNheSI6dHJ1ZSwibW9sZWN1bGUiOnRydWUsInN5bnRoZXNpcyI6dHJ1ZSwiZmluaXNoZWQiOmZhbHNlfSwic3ludGhlc2lzIjp7IkgtcCI6eyJudW1iZXIiOjEwMCwiYWN0aXZlIjoxMDAsImlzX25ldyI6ZmFsc2V9LCJPMyI6eyJudW1iZXIiOjAsImFjdGl2ZSI6MCwiaXNfbmV3IjpmYWxzZX0sIk8yLU9PIjp7Im51bWJlciI6MCwiYWN0aXZlIjowLCJpc19uZXciOmZhbHNlfSwiTzJPMi1PM08iOnsibnVtYmVyIjowLCJhY3RpdmUiOjAsImlzX25ldyI6ZmFsc2V9LCJIMk8iOnsibnVtYmVyIjowLCJhY3RpdmUiOjAsImlzX25ldyI6dHJ1ZX19fQ==`

**Comment by angarg12** [comment]
Currently beta decay produces energy and sub particles. Behind the curtain it also generates He but this is not displayed because He is not implemented in the prototype.
