### ISSUE TITLE
Unlocking New Elements

### ISSUE THREAD

**Issue by stickyfingies** [angarg12/incremental_table_elements#51]
Hi, just wondering: when (approximately) will support be added for new elements and isotopes?  This is a great game, I think the only thing hindering it is the lack of unlockable elements.   Other than that, great game! 👍 💯 🥇

**Comment by angarg12** [comment]
Thank you very much for your feedback, it is greatly appreciated.

The latest development version (the one on this repo) has 10 elements with their isotopes, and lots of reactions. You can play it by cloning the repo and building the code. Something like

`npm install`
`gulp build`

However this code is likely buggy and incomplete.

The idea is to post a beta of the new version soonish. I ran into big problems with ions, so I need to figure out if I completely rebuild the system, or if I leave it for later.  I don't want to make any promise, but the target would be 1-2 months.

**Comment by angarg12** [comment]
A beta for v2 is available here.

https://angarg12.github.io/nucleogenesis/

Up to 10 elements are available.

**Comment by stickyfingies** [comment]
Awesome!  Thanks!
