### ISSUE TITLE
More elements part 2: 11 to 118

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#59]
Currently the game includes elements 1 to 10. We need to fill in the data for the rest of the elements. This is mostly busy work.

The following is a sample of how the Element object looks like.

``` 
"H": {
    "name": "Hydrogen",
    "isotopes": {
      "1H": {
        "ratio": 0.999884
      },
      "2H": {
        "ratio": 0.000115
      },
      "3H": {
        "ratio": 0.000001,
        "decay": {
          "half_life": 3.8852e+8,
          "decay_type": "beta-",
          "decay_product": {
            "3He+": 1,
            "e-": 1,
            "eV": 18610
          }
        }
      }
    },
    "ionization_energy": [13.5984],
    "electron_affinity": [-0.7545, 5.9498],
    "main": "1H",
    "number": 1
  }
``` 

The procedure to fill in the data is the following.

For the isotopes:

* Go to the wikipedia page for each element, e.g. https://en.wikipedia.org/wiki/Hydrogen
* Go down to main isotopes in the side table.
* Add one entry for each isotope.
* The ratio is the NA rounded to 4 decimal places, e.g. the minimum is 0.0001%.
* If an element NA is 'trace', set it to 0.0001% (substract from the most abundant isotope, so that it still sums 1).
* If an element is 'synthetic', its abundance is 0%.
* If an element is radioactive, create a decay entry.
* Normalise half_life and decay energy to seconds and eV respectively.
* Set the decay type and decay product. ~~If more than 1 decay is available, choose the most common one, or an arbitrary one.~~ If more than 1 decay is available, create one entry for each type. If no probability is displayed, set all of them to the same.
* Set main to the most abundant isotope.

For the ionization energy.

* Take the data from [this wiki page](https://en.wikipedia.org/wiki/Ionization_energies_of_the_elements_(data_page)).
* Make sure to take the data in eV.

For the electron affinity.

* Take the data from [this pastebin](https://pastebin.com/X7ne2Bh5).
* If an element is not in the list, it has no known electron affinity, and therefore it is left empty.

Progress

- [x] 11-20
- [x] 21-30
- [ ] 31-40
- [ ] 41-50
- [ ] 51-60
- [ ] 61-70
- [ ] 71-80
- [ ] 81-90
- [ ] 91-100
- [ ] 101-110
- [ ] 111-118

**Comment by JCBoorgo** [comment]
I'm on it! Also, I suppose I have to remove the line with "disabled" in it... I'll leave them there just to be sure for now, I'll just get rid of them if needs be.

**Comment by angarg12** [comment]
Yes, the disabled line has to be removed to be able to buy the element.
