### ISSUE TITLE
More sanity checks in the isotope generation

### ISSUE THREAD

**Issue by angarg12** [angarg12/incremental_table_elements#64]
The isotope generation script should do some sanity checks, like that the total frequency of each isotope sums 1, or guess which is the main isotope for an element.

**Comment by JCBoorgo** [comment]
I think I know how I could do that. I'll come back to do it later. If the frequencies don't add up to 1, should we just not generate anything and log it in the console? Also, should the main be set at elements[resource].main?

**Comment by angarg12** [comment]
Thanks, I'll assign this to you.

If frequencies don't add up to 1, I think we should throw an error, and that would halt the pipeline. 

`throw new Error("xxxxxx");`

Yes, main should be set at elements[resource].main. Once that is in place, we can delete the declaration in the data file.
