### ISSUE TITLE
Upgrades are missing Tier

### ISSUE THREAD

**Issue by pattinsont** [angarg12/incremental_table_elements#71]
Upgrades are missing the Tier they affect. This makes determining which tier an upgrade affects difficult to determine.

**Comment by angarg12** [comment]
Thanks for your report! This is a known issue and 'intentional'. Specifically it relates to #57. We have yet to fill in the data for all upgrades, which is essentially busy work.

We will prioritise this task higher.

**Comment by angarg12** [comment]
Fixed in the last release.
