### ISSUE TITLE
7Be doesn't appear to decay

### ISSUE THREAD

**Issue by pattinsont** [angarg12/incremental_table_elements#72]
Not sure if this is a bug or some aspect of electron capture decay I don't appreciate, but <sub>7</sub>Be doesn't appear to undergo decay. My crude test has 2x10<sup>6</sup> <sub>7</sub>Be, which I would expect to undergo decay in less than 10s, but I'm not seeing the 800k eV jump.

**Comment by angarg12** [comment]
I acknowledge the bug.

**Comment by angarg12** [comment]
This is indeed a problem with all radioactive isotopes.

The radioisotopes.json file is static instead of derived, and only includes 3H.

In order to fix the bug we need to delete the file, create a list of radioisotopes inside generate_isotopes script, and dump it to the radioisotopes.json file.

**Comment by angarg12** [comment]
The update is live, please check if the bug has been fixed.

**Comment by pattinsont** [comment]
This has been resolved. I noticed that <sub>31</sub>Si isn't decaying either. Is there no way of reading _elements.json_ and respecting the decay data there?

**Comment by angarg12** [comment]
31Si is decaying in the live version according to our tests. Did that happen before, or is it happening now?

**Comment by pattinsont** [comment]
If I recall correctly, H decay that results in 3He, created the He tab (but without generators. If that is so, then 31Si decay should result in a 31P product. I haven't got P unlocked, so would expect it to "autopop", (i.e. the P tab becomes available, but without generators, like 3He did in the beginning for H decay).

**Comment by angarg12** [comment]
That's how it works in our current tests. 31Si decays and Phosphorus becomes visible.

If it doesn't work for you we can try to get more info. Does the console show anything? Maybe you can export your save and send it to us.

**Comment by angarg12** [comment]
Fixed! Decay should work now.
