### ISSUE TITLE
More feedback!

### ISSUE THREAD

**Issue by etmoonshade** [angarg12/incremental_table_elements#8]
I actually had a nice long reply written, but then my browser crashed and I lost it. :(

I just want to say that this is a really cool incremental, and I'm happy to see you're working on it again. I look forward to seeing what else you do with it. :D

One thing I wanted to mention (as a response to your word from the developer) is that the pacing is kinda terrible though. When I first played this game, I almost quit because I thought it was just a stupid hydrogen-collecting simulator - with a little bit of 2H and 3H thrown in for variety.

It might be worthwhile to give reality a little bit of a nudge when it comes to unlocking a few things - in other words, your first few tritium decays should come at an accelerated pace, and your second and third element unlocks (presumably He and Li once implemented) should be fairly cheap. This keeps the player engaged, by (indirectly) showing them that yes, there **is** more stuff down the rabbit-hole.

Another thing might be a brief tutorial - something to get players through the first couple of reactions and syntheses. I remember that being fairly confuzzling the first time through, and once again - it says "hey, this is going to be a core gameplay mechanic. There's more!"

What I don't have a good answer to is the question you pose with "The game has no challenge nor goal, and is closer to a toy than a game." The natural progression is to give the player stuff to use their compounds on, but that's a whole other can of worms - even the first set of elements mentioned in #7 has an absolutely huge number of things you can make with them. Maybe make the generators require money to generate stuff, and you can sell compounds? Start off by selling your H2, 2H, and 3H, and then work up to selling more complex compounds, with the framing device of a chemical company?

Just a little bit of an early-morning brain dump from me. :)

**Comment by angarg12** [comment]
First of all thanks for the feedback, it is appreciated.

Do you have any specific estimation of the pacing speed? After implementing the Poisson distribution and my last balance pass, according to my tests it takes about 1 hour to unlock the first decay. In the context of idle games 1 hour seems very reasonable.

If pacing is too slower though it is a problem I need to fix before next release. Ideally I would like to include an in-universe solution.

I could boost numbers but I already did that I want to keep away from inflating generators. Second, I could include a new mechanic that helps to boostrap the game, but doesn't have a big impact long term (e.g. random gamma rays that ionize atoms).

A tangential solution is not to accelerate pace but to tease players to keep going. The game has an unlock counter in the options section but I guess it isn't prominent enough. I like how Mine Defense previews upcoming upgrades.

Regarding tutorials, I don't want to implement one for this game. The spirit of the experience is that the game slowly unfolds in front of you, and gameplay should be the tutorial. By introducing mechanics incrementally players should be able to easily figure out what to do.

Could you describe in detail how or why you found it confusing? In any case I think I will do a playtesting with fresh players to improve the experience.

Lastly I still feel a lack of purpose on the game, but is not something that is bothering me too much right now.

**Comment by etmoonshade** [comment]
> Do you have any specific estimation of the pacing speed? After implementing the Poisson distribution and my last balance pass, according to my tests it takes about 1 hour to unlock the first decay. In the context of idle games 1 hour seems very reasonable.

I guess my thought is that while it's reasonable, I've played quite a lot of incrementals - there was basically nothing to distinguish the start of the game from any other incremental game. Even less so with IToE, because the next upgrade for hours is just... more hydrogen. Even with Cookie Clicker, you get variety and upgrades practically immediately - cursors to grandmas, and teasers for interesting upgrades in the top bar.

> I could boost numbers but I already did that I want to keep away from inflating generators. Second, I could include a new mechanic that helps to boostrap the game, but doesn't have a big impact long term (e.g. random gamma rays that ionize atoms).

I like the second idea. Anything to get you into something other than "ho-hum, more hydrogen."

> A tangential solution is not to accelerate pace but to tease players to keep going. The game has an unlock counter in the options section but I guess it isn't prominent enough. I like how Mine Defense previews upcoming upgrades.

This is actually what kept me from dropping the game the first time around - "okay, it -says- there's more, but it doesn't say how much more... I guess I'll let this idle overnight."

On the point of the teasers, once you get some tritium, you can tease helium over on the right side where the elements go.

> Could you describe in detail how or why you found it confusing? In any case I think I will do a playtesting with fresh players to improve the experience.

Oy, that was a year or more ago. I don't remember for sure, but I think it was not understanding that I wanted more eV so I could do stuff, and how to get there. It may have just been me being derpy - I don't remember anymore. :)

**Comment by angarg12** [comment]
I don't have a definitive answer to regulate pacing. I will try to do playtesting, gather feedback and look into some solutions.

I will also insert a couple of cues for teasing upcoming unlocks.

> On the point of the teasers, once you get some tritium, you can tease helium over on the right side where the elements go.

This will be in an upcoming version. Resources generated via decay or otherwise will give access to those elements, although generators will stay locked until the specific element is purchased.

**Comment by angarg12** [comment]
Since this isn't actionable and feedback has been recorded, the issue will be closed.
