### ISSUE TITLE
Text error: Exotic Matter

### ISSUE THREAD

**Issue by etmoonshade** [angarg12/incremental_table_elements#80]
Under the "Exotic Matter" tab, the display of Hydrogen shows an extra "1" on the end of the exponent as in the following:
You will sacrifice

6.3296 × **10^81H**

88,765 2H

791 3H

**Comment by etmoonshade** [comment]
And duh, it just clicked - it just needs a space between the first exponent and the superscript before the element.

**Comment by angarg12** [comment]
Hello!

Thank you very much for your feedback. GUI will eventually be redesigned so we are not spending too much effort streamlining it.

We made a patch where we put the resources in front to make it easier to read. This will be available online with the next update, which may take a few days to be uploaded.
