### ISSUE TITLE
Redox Reactions not disabled on prestige / DM prestige

### ISSUE THREAD

**Issue by boozledorf** [angarg12/incremental_table_elements#87]
I had a redox reaction enabled that turned my Hydrogen into protons / electrons.  When I converted my Exotic Matter into Dark Matter, I didn't realize this reaction was still going and couldn't figure out why I had no Hydrogen (but was getting plenty of all the other elements I have unlocked).  Perhaps this should be disabled when prestiging.

**Comment by angarg12** [comment]
Hello, indeed this is a mistake from our part. Reactions are disabled on prestige to avoid depletion, and so should redoxes.
