### ISSUE TITLE
Some isotopes are not generated at correct probabilities

### ISSUE THREAD

**Issue by boozledorf** [angarg12/incremental_table_elements#88]
For some reason that I haven't found yet, not all isotopes are being generated at their correct probabilities.  For example, 22Na, which has an occurrence rate of 0.0001%, seems to never generate more than ~800 per second.  I am currently earning 1.9835 × 10^19Na/s, and have 1.3156 × 10^23 23Na and 1.3184 × 10^17 24Na.  In contrast, I only have 5.5477 × 10^6 22Na.
Isotopes that I've unlocked that seem to be affected are:

- 22Na
- 36Cl
- 36Ar
- 38Ar
- 39Ar
- 41Ca

**Comment by boozledorf** [comment]
Possibly related: I have 2.9731 × 10^25 18F, which has a half-life of a little under two hours, and a 96% decay rate into 18O and e+ and a lot of energy, but I only have 2.9058 × 10^7 e+ after leaving the game on for several days.

**Comment by angarg12** [comment]
Both isotope generation and decay are governed by the same rules, so if there is a bug in the system is may be affecting both.

Thanks for the report, I will proceed to investigate.

**Comment by angarg12** [comment]
Acknowledge as bug.

Your observations are totally correct. Here is a sample of Na production.

```
22Na 724
23Na 6.184355257619326e+28
24Na 6.184367626810316e+22
22Na 749
23Na 6.184355257619326e+28
24Na 6.184367626810316e+22
22Na 789
23Na 6.184355257619326e+28
24Na 6.184367626810316e+22
```

**Comment by angarg12** [comment]
There was a long standing bug in the random draw function that was producing wrong values for low probabilities. I checked the isotope generation as well as the decay and now it should work properly.

**Comment by boozledorf** [comment]
Thank you for figuring this out!  However, for some reason, the changes aren't live on the beta version yet.

**Comment by angarg12** [comment]
After some testing I found yet another bug in the same system, so I need to fix that one before going live. Sorry about that.

**Comment by boozledorf** [comment]
That's okay!  Thank you for letting me know, I was just wondering if I was doing anything wrong.

**Comment by angarg12** [comment]
I pushed a workaround that should be live now. I will work a little bit more on dev to check that everything is indeed working properly.

**Comment by angarg12** [comment]
We have completely deleted the Poisson distribution, so this shouldn't happen again.
