### ISSUE TITLE
Game is "stuck"

### ISSUE THREAD

**Issue by boozledorf** [angarg12/incremental_table_elements#93]
The game is "stuck", not producing any elements at all, due to what appears to be a Javascript error:

> TypeError: H is undefined
> Stack trace:
> this.isReactionCostMet@https://angarg12.github.io/nucleogenesis/scripts/app.min.js:1:494646
> this.react@https://angarg12.github.io/nucleogenesis/scripts/app.min.js:1:494838
> n@https://angarg12.github.io/nucleogenesis/scripts/app.min.js:1:505799
> C.update@https://angarg12.github.io/nucleogenesis/scripts/app.min.js:1:496850
> O.update@https://angarg12.github.io/nucleogenesis/scripts/app.min.js:1:493847
> f/q<@https://angarg12.github.io/nucleogenesis/bower_components/angular/angular.min.js:161:437
> e@https://angarg12.github.io/nucleogenesis/bower_components/angular/angular.min.js:48:146
> pg/k.defer/c<@https://angarg12.github.io/nucleogenesis/bower_components/angular/angular.min.js:51:68
>  Possibly unhandled rejection: {}

**Comment by angarg12** [comment]
Thanks for the report.

According to the log there seems to be a malformed reaction that is crashing the game loop.

After looking into the code everything seems to be in order. Could you please email your save so that we can try to reproduce the error?

**Comment by boozledorf** [comment]
Here is a copy of my current save (subatomics might need to be scaled significantly harder in the future):
https://pastebin.com/8mn9hTpJ

**Comment by boozledorf** [comment]
It's possible that some reactions were removed in the recent update, which is causing some errors, because I've "unlocked" them but they don't exist?

**Comment by angarg12** [comment]
You are absolutely right, a few reactions were removed in the latest update.

I will set up a sanity check into the code for the future for good measure.

**Comment by angarg12** [comment]
Just a quick update.

Digging deeper into the issue, the problem is not that reactions where removed. For one of the updates I normalised all the molecules names to Hill notation. So for instance, OH has become HO, but since the reaction key is derived from the name, the game doesn't recognise them anymore.

I don't think I can recover the data without a more involved recovery function.

**Comment by angarg12** [comment]
I pushed a fix to production, please check in a few minutes if it works.

By the way I am amazed by the ridiculous amount of subatomics that you got. You made them out of the infusion multiplication bonus?

**Comment by boozledorf** [comment]
Yes, e- and e+ can be mass-produced from 18F and 31Si, which have sufficiently low half-lives that pouring just 10% of e- and e+ into them after a dark matter prestige will within minutes boost what you already have by a factor of 10^6 or more.  Protons are harder to come by, only available through redoxes with Hydrogen at the moment, and neutrons are currently unavailable without cheating.

**Comment by boozledorf** [comment]
It looks like the fix you pushed is working.  Thank you!
